hawariyyun/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('account.urls')),
    path('absensi/', include('absensi.urls')),
    path('helpdesk/', include('helpdesk.urls')),
    path('survei/', include('survei.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

helpdesk/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index_helpdesk, name="index_helpdesk"),
    path('kritik-dan-saran', views.saran, name="saran"),
    path('pengurus/list-kritik-saran', views.list_kritik_saran, name="list_kritik_saran"),
    path('pengurus/list-kritik', views.list_kritik, name="list_kritik"),
    path('pengurus/list-saran', views.list_saran, name="list_saran"),
    path('pengurus/list-kritik-saran/nama', views.list_nama, name="list_nama"),
    path('pengurus/update_kritik_saran/<int:id>', views.update_kritik_saran, name="update_kritik_saran"),
]

main/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name="index"),
    path('sekretaris', views.sekretaris, name="sekretaris"),
]

helpdesk/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.
status = (
	(1,'Diajukan'),
	(2,'Diproses'),
    (3,'Selesai'),
)
jenis = (
	(1,'Kritik'),
	(2,'Saran')
)


class kritik_saran(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE,related_name='kritik_saran' , blank = True , null = True )
    jenis = models.IntegerField(choices = jenis)
    pembahasan = models.CharField(max_length=5000)
    status = models.IntegerField(choices = status ,default=1)
    date_posted = models.DateTimeField(default=timezone.now)
    

helpdesk/forms.py
from dataclasses import fields
from pyexpat import model
from tkinter.tix import Select
from django.core import validators
from django import forms
from .models import kritik_saran


class JenisForm(forms.ModelForm):
     class Meta:
        model = kritik_saran
        fields = ['jenis','pembahasan']
        widgets = { 
            'jenis': forms.Select(attrs={'class':'form-control'}),
            'pembahasan': forms.Textarea(attrs={'class':'form-control'}),
            
        }

class TeknisiForm(forms.ModelForm):
     class Meta:
        model = kritik_saran
        fields = [ 'status' ]
        widgets = { 
            'status': forms.Select(attrs={'class':'form-control'}),
            
        }



helpdesk/views.py
from django.shortcuts import render,redirect,HttpResponse
from .models import kritik_saran
from account.models import Profile
from .forms import TeknisiForm
from django.contrib.auth.decorators import login_required
from .forms import JenisForm
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages

def administration(user):
    return user.groups.filter(name='sekretaris').exists()
# Create your views here.

# function untuk menambahkan

# Create your views here.
TEMPLATE_DIRS = (
    'os.path.join(BASE_DIR, "templates"),'
)

def index_helpdesk(request):
    return render(request, 'index_helpdesk.html')


# def update_informasi_keluhan(request, id):
#   if request.method == 'POST':
#     print("tes")
#     pi = FileUpload.objects.get(pk=id)
#     fm = TeknisiFileUploadForm(request.POST,request.FILES, instance=pi)
#     if fm.is_valid():
#       fm.save()
#       return redirect('tampilan_gambar')
#   else:
#     pi = FileUpload.objects.get(pk=id)
#     fm = TeknisiFileUploadForm(instance=pi)
#   return render(request, 'update_file.html', {'form':fm})


@login_required(login_url='customerlogin')
@user_passes_test(administration,login_url='index_helpdesk')
def update_kritik_saran(request, id):
  if request.method == 'POST':
    pi = kritik_saran.objects.get(pk=id)
    fm = TeknisiForm(request.POST, instance=pi)
    if fm.is_valid():
      fm.save()
      return redirect('list_kritik_saran')
  else:
    pi = kritik_saran.objects.get(pk=id)
    fm = TeknisiForm(instance=pi)
  context ={
     'form':fm,
     'pi':pi
  }
  return render(request, 'pengurus/update_kritik_saran.html',context)


@login_required(login_url='customerlogin')
def saran(request):
   profil = Profile.objects.get(user = request.user)
   cek = Profile.objects.filter(user = request.user, role = 7).exists()
   if request.method == 'POST':
        form = JenisForm(request.POST, request.FILES)
        print(form.as_p)
        if form.is_valid():
            user = request.user
            jenis = form.cleaned_data['jenis']
            pembahasan = form.cleaned_data['pembahasan']
            status = 1
            kritik_saran(user = user, jenis=jenis,pembahasan=pembahasan, status=status).save()
            messages.success(request,'Terima kasih atas kritik atau saran nya :)')
            return redirect('index_helpdesk')
        else:
            messages.error(request, 'Data tidak bisa terkirim :)')
            return redirect('index_helpdesk')
   else:
        context = {
            'form':JenisForm(),
            'cek':cek
        }
   return render(request, 'saran.html',context)
@login_required
@user_passes_test(administration,login_url='index_helpdesk')
def list_kritik_saran(request):
    pengurus = Profile.objects.get(user = request.user)
    saran = kritik_saran.objects.all().order_by('-date_posted')
    context = {
        'pengurus':pengurus,
        'saran':saran,
    }
    return render(request, 'pengurus/list_kritik_saran.html',context)
@login_required
@user_passes_test(administration,login_url='index_helpdesk')
def list_kritik(request):
    pengurus = Profile.objects.get(user = request.user)
    saran = kritik_saran.objects.filter(jenis = 1)
    context = {
        'pengurus':pengurus,
        'saran':saran,
    }
    return render(request, 'pengurus/list_kritik.html',context)
@login_required
@user_passes_test(administration,login_url='index_helpdesk')
def list_saran(request):
    pengurus = Profile.objects.get(user = request.user)
    saran = kritik_saran.objects.filter(jenis = 2)
    context = {
        'pengurus':pengurus,
        'saran':saran,
    }
    return render(request, 'pengurus/list_saran.html',context)

@login_required
@user_passes_test(administration,login_url='index_helpdesk')
def list_nama(request):
    pengurus = Profile.objects.get(user = request.user)
    saran = kritik_saran.objects.all()
    if request.method == "POST":
        pencarian = request.POST['pencarian']
        hasil = kritik_saran.objects.filter(user__first_name__contains=pencarian)
        context = {
            'pengurus':pengurus,
            'saran':saran,
            'hasil':hasil,
            'pencarian':pencarian
        }
        return render(request, 'pengurus/list_nama.html',context)
    else:
        return render(request, 'pengurus/list_nama.html',{})

helpdesk/templates/pengurus/list_kritik.html
{% extends 'base_main.html' %}{% load static %} {% block content %}
<style>
  form .btn-submit {
    display: flex;
    background: black;
    color: white;
    padding: 0.5em;
    border-radius: 5px;
    width: 150px;
    cursor: pointer;
  }
  form .btn-submit:focus {
    color: black;
    background: white;
    border: 1px solid black;
  }
  form .btn-submit .link-submit {
    font-size: 14px;
    text-align: center;
    color: white;
    width: 150px;
  }
  form .btn-submit .link-submit:focus {
    font-size: 14px;
    text-align: center;
    color: black;
  }
</style>
<body>
  <header class="hero">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-6 col-xs-12">
          <nav>
            <div id="menu-toggle">
              <div class="hamburger">
                <span class="line"></span>
                <span class="line"></span>
                <span class="line"></span>
              </div>
              <div class="cross">
                <span class="line"></span>
                <span class="line"></span>
              </div>
            </div>
            <ul class="main-nav">
              <li><a href="{% url 'index_helpdesk' %}">Home</a></li>
              <li><a href="{% url 'list_kritik_saran' %}">Pengurus LC</a></li>
            </ul>
          </nav>
          <div class="hero-text">
            <h1>{{pengurus.get_role_display}}<span></span></h1>
            <h3></h3>
            {% if request.user.is_authenticated %}
            <h3>Selamat datang {{pengurus.user}} !</h3>
            {% else %}
            <a href="{% url 'register' %}" class="btn btn-lg btn-primary">Daftar/Masuk</a>
            {% endif %}
            <ul class="social-links" style="margin-top: 2em">
              <li class="label">Follow me</li>
              <li>
                <a href="#"><img src="{% static 'maria/assets/twitter.png' %}" /></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </header>

  <section class="case-study">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h4 class="sub-heading">event</h4>
          <h1 class="heading purple">
            <span class="blue">Service</span><br />
            Kritik dan Saran kalian tentang kami
          </h1>
          <!-- Swiper -->
          <div class="swiper-container client-swiper" style="max-height: 400px; overflow: auto">
            <div class="filter" style="margin-bottom: 2em" style="display: flex">
              <a href="{% url 'list_saran' %}" class="btn btn-primary" style="margin-bottom: 2em">Saran </a>
              <a href="{% url 'list_kritik' %}" class="btn btn-primary" style="margin-bottom: 2em">Kritik </a>
              <form class="form-inline my-2 my-lg-0" style="display: flex; flex-direction: row" method="POST" action="{% url 'list_nama' %}">
                {% csrf_token %}
                <input class="form-control mr-sm-2 col-sm-2" type="search" placeholder="cari nama depan.." aria-label="Search" name="pencarian" />
                <button class="btn btn-primary" type="submit">Cari</button>
              </form>
            </div>
            {% if request.user.is_authenticated %}

            <table class="table">
              <thead>
                <tr>
                  <th scope="col">No</th>
                  <th scope="col">Nama</th>
                  <th scope="col">Jenis</th>
                  <th scope="col">Status</th>
                  <th scope="col">Action</th>
                </tr>
              </thead>
              <tbody>
                {% for i in saran %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{i.user.first_name}} {{i.user.last_name}}</td>
                  <td>{{i.get_jenis_display}}</td>
                  <td>{{i.get_status_display}}</td>
                  <td>
                    <a href="{% url 'update_kritik_saran' i.id %}" class="btn btn-warning">Update</a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% else %}
            <h2 class="alert text-center">Login terlebih dahulu untuk bisa memberikan kritik dan saran</h2>
          </div>
          <!-- Add Arrows -->

          {% endif %}
        </div>
      </div>
    </div>
  </section>

  <!-- Footer -->
  <footer>
    <div class="container-fluid">
      <div class="row footer">
        <div class="col-md-12 text-center">
          <h1>
            <span><img src="{% static 'logo-biru.png' %}" style="height: 200px; margin-top: -1em" /></span>
          </h1>
          <ul class="social-links">
            <li>
              <a href="#"><img src="{% static 'maria/assets/twitter.png' %}" /></a>
            </li>
          </ul>
        </div>
      </div>
      <div class="row sub-footer">
        <div class="col-md-12 text-center">
          <p>Developed by <a href="https://instagram.com/medkomlc_11">Media Komunikasi</a></p>
        </div>
      </div>
    </div>
  </footer>
</body>

{% endblock content %}

helpdesk/templates/pengurus/list_kritik_saran.html
{% extends 'base_main.html' %}{% load static %} {% block content %}
<style>
  form .btn-submit {
    display: flex;
    background: black;
    color: white;
    padding: 0.5em;
    border-radius: 5px;
    width: 150px;
    cursor: pointer;
  }
  form .btn-submit:focus {
    color: black;
    background: white;
    border: 1px solid black;
  }
  form .btn-submit .link-submit {
    font-size: 14px;
    text-align: center;
    color: white;
    width: 150px;
  }
  form .btn-submit .link-submit:focus {
    font-size: 14px;
    text-align: center;
    color: black;
  }
</style>
<body>
  <header class="hero">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-6 col-xs-12">
          <nav>
            <div id="menu-toggle">
              <div class="hamburger">
                <span class="line"></span>
                <span class="line"></span>
                <span class="line"></span>
              </div>
              <div class="cross">
                <span class="line"></span>
                <span class="line"></span>
              </div>
            </div>
            <ul class="main-nav">
              <li><a href="{% url 'index_helpdesk' %}">Home</a></li>
              <li><a href="{% url 'list_kritik_saran' %}">Pengurus LC</a></li>
            </ul>
          </nav>
          <div class="hero-text">
            <h1>{{pengurus.get_role_display}}<span></span></h1>
            <h3></h3>
            {% if request.user.is_authenticated %}
            <h3>Selamat datang {{pengurus.user}} !</h3>
            {% else %}
            <a href="{% url 'register' %}" class="btn btn-lg btn-primary">Daftar/Masuk</a>
            {% endif %}
            <ul class="social-links" style="margin-top: 2em">
              <li class="label">Follow me</li>
              <li>
                <a href="#"><img src="{% static 'maria/assets/twitter.png' %}" /></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </header>

  <section class="case-study">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h4 class="sub-heading">event</h4>
          <h1 class="heading purple">
            <span class="blue">Service</span><br />
            Kritik dan Saran kalian tentang kami
          </h1>
          <!-- Swiper -->
          <div class="swiper-container client-swiper" style="max-height: 400px; overflow: auto">
            <div class="filter" style="margin-bottom: 2em" style="display: flex">
              <a href="{% url 'list_saran' %}" class="btn btn-primary" style="margin-bottom: 2em">Saran </a>
              <a href="{% url 'list_kritik' %}" class="btn btn-primary" style="margin-bottom: 2em">Kritik </a>
              <form class="form-inline my-2 my-lg-0" style="display: flex; flex-direction: row" method="POST" action="{% url 'list_nama' %}">
                {% csrf_token %}
                <input class="form-control mr-sm-2 col-sm-2" type="search" placeholder="cari nama depan.." aria-label="Search" name="pencarian" />
                <button class="btn btn-primary" type="submit">Cari</button>
              </form>
            </div>
            {% if request.user.is_authenticated %}

            <table class="table">
              <thead>
                <tr>
                  <th scope="col">No</th>
                  <th scope="col">Nama</th>
                  <th scope="col">Jenis</th>
                  <th scope="col">Status</th>
                  <th scope="col">Action</th>
                </tr>
              </thead>
              <tbody>
                {% for i in saran %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{i.user.first_name}} {{i.user.last_name}}</td>
                  <td>{{i.get_jenis_display}}</td>
                  <td>{{i.get_status_display}}</td>
                  <td>
                    <a href="{% url 'update_kritik_saran' i.id %}" class="btn btn-warning">Update</a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% else %}
            <h2 class="alert text-center">Login terlebih dahulu untuk bisa memberikan kritik dan saran</h2>
          </div>
          <!-- Add Arrows -->

          {% endif %}
        </div>
      </div>
    </div>
  </section>

  <!-- Footer -->
  <footer>
    <div class="container-fluid">
      <div class="row footer">
        <div class="col-md-12 text-center">
          <h1>
            <span><img src="{% static 'logo-biru.png' %}" style="height: 200px; margin-top: -1em" /></span>
          </h1>
          <ul class="social-links">
            <li>
              <a href="#"><img src="{% static 'maria/assets/twitter.png' %}" /></a>
            </li>
          </ul>
        </div>
      </div>
      <div class="row sub-footer">
        <div class="col-md-12 text-center">
          <p>Developed by <a href="https://instagram.com/medkomlc_11">Media Komunikasi</a></p>
        </div>
      </div>
    </div>
  </footer>
</body>

{% endblock content %}

helpdesk/templates/pengurus/list_nama.html
{% extends 'base_main.html' %}{% load static %} {% block content %}
<style>
  form .btn-submit {
    display: flex;
    background: black;
    color: white;
    padding: 0.5em;
    border-radius: 5px;
    width: 150px;
    cursor: pointer;
  }
  form .btn-submit:focus {
    color: black;
    background: white;
    border: 1px solid black;
  }
  form .btn-submit .link-submit {
    font-size: 14px;
    text-align: center;
    color: white;
    width: 150px;
  }
  form .btn-submit .link-submit:focus {
    font-size: 14px;
    text-align: center;
    color: black;
  }
</style>
<body>
  <header class="hero">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-6 col-xs-12">
          <nav>
            <div id="menu-toggle">
              <div class="hamburger">
                <span class="line"></span>
                <span class="line"></span>
                <span class="line"></span>
              </div>
              <div class="cross">
                <span class="line"></span>
                <span class="line"></span>
              </div>
            </div>
            <ul class="main-nav">
              <li><a href="{% url 'index_helpdesk' %}">Home</a></li>
              <li><a href="{% url 'list_kritik_saran' %}">Pengurus LC</a></li>
            </ul>
          </nav>
          <div class="hero-text">
            <h1>{{pengurus.get_role_display}}<span></span></h1>
            <h3></h3>
            {% if request.user.is_authenticated %}
            <h3>Selamat datang {{pengurus.user}} !</h3>
            {% else %}
            <a href="{% url 'register' %}" class="btn btn-lg btn-primary">Daftar/Masuk</a>
            {% endif %}
            <ul class="social-links" style="margin-top: 2em">
              <li class="label">Follow me</li>
              <li>
                <a href="#"><img src="{% static 'maria/assets/twitter.png' %}" /></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </header>

  <section class="case-study">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h4 class="sub-heading">event</h4>
          <h1 class="heading purple">
            <span class="blue">Service</span><br />
            Kritik dan Saran kalian tentang kami
          </h1>
          <!-- Swiper -->
          <div class="swiper-container client-swiper" style="max-height: 400px; overflow: auto">
            <div class="filter" style="margin-bottom: 2em" style="display: flex">
              <a href="{% url 'list_saran' %}" class="btn btn-primary" style="margin-bottom: 2em">Saran </a>
              <a href="{% url 'list_kritik' %}" class="btn btn-primary" style="margin-bottom: 2em">Kritik </a>
              <form class="form-inline my-2 my-lg-0" style="display: flex; flex-direction: row" method="POST" action="{% url 'list_nama' %}">
                {% csrf_token %}
                <input class="form-control mr-sm-2 col-sm-2" type="search" placeholder="cari nama depan.." aria-label="Search" name="pencarian" />
                <button class="btn btn-primary" type="submit">Cari</button>
              </form>
            </div>
            {% if request.user.is_authenticated %}

            <table class="table">
              <thead>
                <tr>
                  <th scope="col">No</th>
                  <th scope="col">Nama</th>
                  <th scope="col">Jenis</th>
                  <th scope="col">Status</th>
                  <th scope="col">Action</th>
                </tr>
              </thead>
              <tbody>
                {% for i in hasil %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{i.user.first_name}} {{i.user.last_name}}</td>
                  <td>{{i.get_jenis_display}}</td>
                  <td>{{i.get_status_display}}</td>
                  <td>
                    <a href="{% url 'update_kritik_saran' i.id %}" class="btn btn-warning">Update</a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% else %}
            <h2 class="alert text-center">Login terlebih dahulu untuk bisa memberikan kritik dan saran</h2>
          </div>
          <!-- Add Arrows -->

          {% endif %}
        </div>
      </div>
    </div>
  </section>

  <!-- Footer -->
  <footer>
    <div class="container-fluid">
      <div class="row footer">
        <div class="col-md-12 text-center">
          <h1>
            <span><img src="{% static 'logo-biru.png' %}" style="height: 200px; margin-top: -1em" /></span>
          </h1>
          <ul class="social-links">
            <li>
              <a href="#"><img src="{% static 'maria/assets/twitter.png' %}" /></a>
            </li>
          </ul>
        </div>
      </div>
      <div class="row sub-footer">
        <div class="col-md-12 text-center">
          <p>Developed by <a href="https://instagram.com/medkomlc_11">Media Komunikasi</a></p>
        </div>
      </div>
    </div>
  </footer>
</body>

{% endblock content %}

helpdesk/templates/pengurus/list_saran.html
{% extends 'base_main.html' %}{% load static %} {% block content %}
<style>
  form .btn-submit {
    display: flex;
    background: black;
    color: white;
    padding: 0.5em;
    border-radius: 5px;
    width: 150px;
    cursor: pointer;
  }
  form .btn-submit:focus {
    color: black;
    background: white;
    border: 1px solid black;
  }
  form .btn-submit .link-submit {
    font-size: 14px;
    text-align: center;
    color: white;
    width: 150px;
  }
  form .btn-submit .link-submit:focus {
    font-size: 14px;
    text-align: center;
    color: black;
  }
</style>
<body>
  <header class="hero">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-6 col-xs-12">
          <nav>
            <div id="menu-toggle">
              <div class="hamburger">
                <span class="line"></span>
                <span class="line"></span>
                <span class="line"></span>
              </div>
              <div class="cross">
                <span class="line"></span>
                <span class="line"></span>
              </div>
            </div>
            <ul class="main-nav">
              <li><a href="{% url 'index_helpdesk' %}">Home</a></li>
              <li><a href="{% url 'list_kritik_saran' %}">Pengurus LC</a></li>
            </ul>
          </nav>
          <div class="hero-text">
            <h1>{{pengurus.get_role_display}}<span></span></h1>
            <h3></h3>
            {% if request.user.is_authenticated %}
            <h3>Selamat datang {{pengurus.user}} !</h3>
            {% else %}
            <a href="{% url 'register' %}" class="btn btn-lg btn-primary">Daftar/Masuk</a>
            {% endif %}
            <ul class="social-links" style="margin-top: 2em">
              <li class="label">Follow me</li>
              <li>
                <a href="#"><img src="{% static 'maria/assets/twitter.png' %}" /></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </header>

  <section class="case-study">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h4 class="sub-heading">event</h4>
          <h1 class="heading purple">
            <span class="blue">Service</span><br />
            Kritik dan Saran kalian tentang kami
          </h1>
          <!-- Swiper -->
          <div class="swiper-container client-swiper" style="max-height: 400px; overflow: auto">
            <div class="filter" style="margin-bottom: 2em" style="display: flex">
              <a href="{% url 'list_saran' %}" class="btn btn-primary" style="margin-bottom: 2em">Saran </a>
              <a href="{% url 'list_kritik' %}" class="btn btn-primary" style="margin-bottom: 2em">Kritik </a>
              <form class="form-inline my-2 my-lg-0" style="display: flex; flex-direction: row" method="POST" action="{% url 'list_nama' %}">
                {% csrf_token %}
                <input class="form-control mr-sm-2 col-sm-2" type="search" placeholder="cari nama depan.." aria-label="Search" name="pencarian" />
                <button class="btn btn-primary" type="submit">Cari</button>
              </form>
            </div>
            {% if request.user.is_authenticated %}

            <table class="table">
              <thead>
                <tr>
                  <th scope="col">No</th>
                  <th scope="col">Nama</th>
                  <th scope="col">Jenis</th>
                  <th scope="col">Status</th>
                  <th scope="col">Action</th>
                </tr>
              </thead>
              <tbody>
                {% for i in saran %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{i.user.first_name}} {{i.user.last_name}}</td>
                  <td>{{i.get_jenis_display}}</td>
                  <td>{{i.get_status_display}}</td>
                  <td>
                    <a href="{% url 'update_kritik_saran' i.id %}" class="btn btn-warning">Update</a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% else %}
            <h2 class="alert text-center">Login terlebih dahulu untuk bisa memberikan kritik dan saran</h2>
          </div>
          <!-- Add Arrows -->

          {% endif %}
        </div>
      </div>
    </div>
  </section>

  <!-- Footer -->
  <footer>
    <div class="container-fluid">
      <div class="row footer">
        <div class="col-md-12 text-center">
          <h1>
            <span><img src="{% static 'logo-biru.png' %}" style="height: 200px; margin-top: -1em" /></span>
          </h1>
          <ul class="social-links">
            <li>
              <a href="#"><img src="{% static 'maria/assets/twitter.png' %}" /></a>
            </li>
          </ul>
        </div>
      </div>
      <div class="row sub-footer">
        <div class="col-md-12 text-center">
          <p>Developed by <a href="https://instagram.com/medkomlc_11">Media Komunikasi</a></p>
        </div>
      </div>
    </div>
  </footer>
</body>

{% endblock content %}